# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 10

image:
  repository: gcr.io/cw-event-logs-service/restapi:v1
  pullPolicy: Always

application:
  name: rest-api